export const TILE_SELECT = 'TILE_SELECT';
export const TILE_UNSELECT = 'TILE_UNSELECT';
export const TILE_REMOVE_UNIT = 'TILE_REMOVE_UNIT';
export const TILE_PLACE_UNIT = 'TILE_PLACE_UNIT';

export const UNIT_REDUCE_HP = 'UNIT_REDUCE_HP';
export const UNIT_SET_ENERGY = 'UNIT_ENERGY_SET';

export const CURRENT_PLAYER_TURN_END = 'CURRENT_PLAYER_TURN_END';
export const PLAYER_GAME_END = 'PLAYER_GAME_END';

export const GAME_OVER = 'GAME_OVER';
