const MAP_DEFINITION = {
  WIDTH: 10,
  HEIGHT: 8,
};

const TILE_CODES = {
  EMPTY: 0, // don't use
  GROUND: 1,
  GRASS: 2,
  WATER: 3,
  SAND: 4,
};

const RANGE_CODES = {
  EMPTY: 0,
  MOVEMENT: 1,
  COMBAT: 2,
};

const UNIT_CODES = {
  EMPTY: 0,
  PAWN: 1,
  KNIGHT: 2,
  BISHOP: 3,
};

const GAME_PHASE = {
  TITLE: 'TITLE',
  SETUP_GAME: 'SETUP_GAME',
  SETUP_PLAYERS: 'SETUP_PLAYERS',
  SETUP_WORLD: 'SETUP_WORLD',
  SETUP_UNITS: 'SETUP_UNITS',
  SETUP_UNIT_PLACEMENT: 'SETUP_UNIT_PLACEMENT',
  // Game generally stays within PLAYER_TURN_....
  PLAYER_TURN_BEFORE: 'PLAYER_TURN_BEFORE',
  PLAYER_TURN: 'PLAYER_TURN',
  PLAYER_TURN_COMBAT_BEFORE: 'PLAYER_TURN_COMBAT_BEFORE',
  PLAYER_TURN_COMBAT: 'PLAYER_TURN_COMBAT',
  PLAYER_TURN_COMBAT_AFTER: 'PLAYER_TURN_COMBAT_AFTER',
  PLAYER_TURN_AFTER: 'PLAYER_TURN_AFTER',
  GAME_OVER: 'GAME_OVER',
};

const UNIT_BEHAVIOUR = {
  MOVE_AND_ACTION: 'MOVE_AND_ACTION',
  MOVE_OR_ACTION: 'MOVE_OR_ACTION',
};

const PLAYER_STATE = {
  IDLE: 'IDLE',
  SELECTED_TILE: 'SELECTED_TILE',
};

export default {
  MAP_DEFINITION,
  RANGE_CODES,
  GAME_PHASE,
  UNIT_BEHAVIOUR,
  PLAYER_STATE,
  TILE_CODES,
  UNIT_CODES,
};
