const MAP_DEFINITION = {
  WIDTH: 10,
  HEIGHT: 8,
};

const RANGE_CODES = {
  EMPTY: 0,
  MOVEMENT: 1,
  COMBAT: 2,
};

const GAME_PHASE = {
  TITLE: 'TITLE',
  SETUP: 'SETUP',
  PLACEMENT: 'PLACEMENT',
  PLAYER_TURN: 'PLAYER_TURN',
  GAME_OVER: 'GAME_OVER',
};

const UNIT_BEHAVIOUR = {
  MOVE_AND_ACTION: 'MOVE_AND_ACTION',
  MOVE_OR_ACTION: 'MOVE_OR_ACTION',
};

export default {
  MAP_DEFINITION,
  RANGE_CODES,
  GAME_PHASE,
  UNIT_BEHAVIOUR,
};
